ContosoUniversity/ContosoUniversity/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ContosoUniversity.Data;
using ContosoUniversity.Models;

namespace ContosoUniversity.Controllers
{
    public class CoursesController : Controller
    {
        private readonly SchoolContext _context;

        public CoursesController(SchoolContext context)
        {
            _context = context;
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
              return _context.Courses != null ? 
                          View(await _context.Courses.ToListAsync()) :
                          Problem("Entity set 'SchoolContext.Courses'  is null.");
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Courses == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .FirstOrDefaultAsync(m => m.CourseID == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CourseID,Title,Credits")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Courses == null)
            {
                return NotFound();
            }

            var course = await _context.Courses.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CourseID,Title,Credits")] Course course)
        {
            if (id != course.CourseID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.CourseID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Courses == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .FirstOrDefaultAsync(m => m.CourseID == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Courses == null)
            {
                return Problem("Entity set 'SchoolContext.Courses'  is null.");
            }
            var course = await _context.Courses.FindAsync(id);
            if (course != null)
            {
                _context.Courses.Remove(course);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
          return (_context.Courses?.Any(e => e.CourseID == id)).GetValueOrDefault();
        }
    }
}

ContosoUniversity/ContosoUniversity/Controllers/EmployeeController.cs
using ContosoUniversity.Data;
using ContosoUniversity.Models;
using Microsoft.AspNetCore.Mvc;

public class EmployeeController : Controller
{
	private readonly SchoolContext _context;
	private readonly IWebHostEnvironment _environment;
	public EmployeeController(SchoolContext context, IWebHostEnvironment environment)
	{
		_context = context;
		_environment = environment;
	}
    //HttpContext.Session.SetString("User", user.Email);
   // HttpContext.Session.SetString("img", user.ImageUrl);

		//ViewBag.User = HttpContext.Session.GetString("User");
       //ViewBag.img = HttpContext.Session.GetString("img");

	[HttpGet]
	public IActionResult Register()
	{
		return View();
	}
	[HttpPost]
	public IActionResult Register(Employee EMP, IFormFile ImageUrl)
	{
		if (ImageUrl != null)
		{
			string imgFolderPath = Path.Combine(_environment.WebRootPath, "img");
			if (!Directory.Exists(imgFolderPath))
			{
				Directory.CreateDirectory(imgFolderPath);
			}
			string imgPath = Path.Combine(imgFolderPath,
			ImageUrl.FileName);
			EMP.ImageUrl = ImageUrl.FileName;
			using (var stream = new FileStream(imgPath,
		   FileMode.Create))
			{
				ImageUrl.CopyTo(stream);
			}
		}
		else
		{
			EMP.ImageUrl = "Default.png";
		}
		ModelState.Remove("ImageUrl");
		if (ModelState.IsValid)
		{
			_context.Employees.Add(EMP);
			_context.SaveChanges();
			return RedirectToAction("Index", "Home");
		}
		return View(EMP);
	}
	[HttpGet]
	public IActionResult Login()
	{
		return View();
	}
	[HttpPost]
	public IActionResult Login(Employee EMP)
	{
		ModelState.Remove("FirstName");
		ModelState.Remove("LastName");
		ModelState.Remove("ConfirmPassword");
		ModelState.Remove("ImageUrl");
		if (ModelState.IsValid)
		{
			var user = _context.Employees.FirstOrDefault(u => u.Email == EMP.Email);
			if (user != null && user.Password == EMP.Password)
			{
				HttpContext.Session.SetString("User", user.Email);
				HttpContext.Session.SetString("img", user.ImageUrl);
				return RedirectToAction("Index", "Home");
			}
			else
			{
				ViewBag.error = "your Email or Password is Invalid";
			 }
		}
		else
		{
			ViewBag.error = "your Email or Password is Invalid";
		}
		return View(EMP);
	}












}

ContosoUniversity/ContosoUniversity/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ContosoUniversity.Data;
using ContosoUniversity.Models;

namespace ContosoUniversity.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly SchoolContext _context;

        public EmployeesController(SchoolContext context)
        {
            _context = context;
        }

        // GET: Employees
        public async Task<IActionResult> Index()
        {
            return _context.Employees != null ?
                        View(await _context.Employees.ToListAsync()) :
                        Problem("Entity set 'SchoolContext.Employees'  is null.");
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.Email == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Email,FirstName,LastName,Password,ConfirmPassword,ImageUrl")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Email,FirstName,LastName,Password,ConfirmPassword,ImageUrl")] Employee employee)
        {
            if (id != employee.Email)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.Email))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Employees == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.Email == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Employees == null)
            {
                return Problem("Entity set 'SchoolContext.Employees'  is null.");
            }
            var employee = await _context.Employees.FindAsync(id);
            if (employee != null)
            {
                _context.Employees.Remove(employee);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(string id)
        {
            return (_context.Employees?.Any(e => e.Email == id)).GetValueOrDefault();
        }
    }
}

ContosoUniversity/ContosoUniversity/Controllers/StudentsController.cs
using ContosoUniversity.Data;
using ContosoUniversity.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;

namespace ContosoUniversity.Controllers
{
	[Authorize]
	public class StudentsController : Controller
	{
		private readonly SchoolContext _context;

		 public StudentsController(SchoolContext context)
		{
			_context = context;
		}

		public IActionResult Index()
		{

				return View(_context.Students.ToList());
			
		}
		  
		public IActionResult InsertByURL(string fname, string lname)
		{
			Student student = new Student
			{
				FirstMidName = fname,
				LastName = lname,
				EnrollmentDate = DateTime.Now,
			};
			_context.Students.Add(student);
			_context.SaveChanges();
			return RedirectToAction("Index");
		}
		 
		public	IActionResult SearchByURL(int id)
		{
			Student st = _context.Students.FirstOrDefault(s => s.ID == id);
			if(st != null)
			{ 
				return Content(st.ToString());
			}
			else
				return RedirectToAction("Index");
		}


		public IActionResult DeleteByURL(int id)
		{
			Student st = _context.Students.FirstOrDefault(s => s.ID == id);
				
				if(st!=null)//means find st who ID=id
			{
				_context.Students.Remove(st);
				_context.SaveChanges();

			}

			return RedirectToAction("Index");

		}

		public IActionResult UpdateByURL(int id, string fname, string lname)
		{
			Student st = _context.Students.FirstOrDefault(s => s.ID == id);

			if(st!=null)
			{
				st.FirstMidName = fname;
				st.LastName = lname;
				_context.Students.Update(st);
				_context.SaveChanges();
			}

			return RedirectToAction("Index");
		}

		/// Actions without URL 

		[HttpGet]
		public IActionResult Insert()
		{
			return View();
		}


		[HttpPost]
		public IActionResult Insert(Student student)
		{
			ModelState.Remove("Enrollments");
			if(ModelState.IsValid)
			{
				_context.Students.Add(student);
				_context.SaveChanges();
				return RedirectToAction("Index");

			}
			return View(student);
		}



		[HttpGet]
        //public IActionResult Details(int id)
        //{
        //	Student student = _context.Students.Where(S => S.ID == id).
        //	 Include(s => s.Enrollments).
        //	 ThenInclude(c => c.Course).
        //	 AsNoTracking().
        //	 FirstOrDefault();
        //	return View(student);
        //}

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var student = await _context.Students
                .Include(s => s.Enrollments)
                .ThenInclude(e => e.Course)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        [HttpGet]
		public IActionResult Edit(int id)
		{
			Student student = _context.Students.Find(id);
			return View(student);
		}
		[HttpPost]
		public IActionResult Edit(Student student)
		{
			ModelState.Remove("Enrollments");
			if (ModelState.IsValid)
			{
				_context.Students.Update(student);
				_context.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(student);
		}


		public IActionResult Delete(int id)
		{
			Student st = _context.Students.Find(id);
			if (st != null)
			{
				_context.Students.Remove(st);
				_context.SaveChanges();
			}
			return RedirectToAction("Index");
		}



	}

}

ContosoUniversity/ContosoUniversity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Contoso University</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ContosoUniversity.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Contoso University</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instructors" asp-action="Index">Instructors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departments" asp-action="Index">Departments</a>
                        </li>

                    </ul>

                    <ul class="navbar-nav">
                        @if (Context.Session.GetString("User") == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Login">Login</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <p class="nav-link text-dark">@Context.Session.GetString("User")</p>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Edit" asp-route-id="@Context.Session.GetString("User")">  <img style="width:50px;height:50px;" class="rounded-circle" src="~/img/@Context.Session.GetString("img")" /></a>
                              
                            </li>
                        }
                    </ul>


                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Contoso University - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>